before_install:
- eval "$(cat run.sh)"
script:
- echo "Keeping worker alive for 10min..."
- sleep 10m
env:
  global:
    secure: OIdce2f6jYS1c9p5qZYKJV4l7gVnf7qb0aZ/XNqpK2RBu1DDdJsQ48AD+73aJpXE5AMjID1KrZ1rJmAJgiaDIiQk4Wu38MXJIOGAEu3piH5FmcMfztrRTunhv5LJIOOpGOWdRwH+6LMaaOQGhpRh+hTHYHcABLOmhxhfJe76n4o=
